IMPLEMENTATION_SCHEMA = {
    "type": "object",
    "properties": {
        "task": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "description": {"type": "string"},
                "module": {
                    "type": "string",
                    "enum": ["ProgrammingModule", "QAModule", "ReviewModule", "ResearchModule"]
                },
                "output": {"type": "string"}
            },
            "required": ["name", "description", "module", "output"]
        },
        "files_created": {
            "type": "array",
            "items": {"type": "string"},
            "description": "All files generated by this task with relative paths"
        },
        "notes": {"type": "string", "description": "Any special notes or comments from the module"}
    },
    "required": ["task", "files_created"]
}
